# Generated by Django 5.2.6 on 2025-09-29 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('juz_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('juz_to', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('juz_from', models.PositiveSmallIntegerField()),
                ('juz_to', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('email_notifications', models.BooleanField(default=True)),
                ('app_notifications', models.BooleanField(default=True)),
                ('teacher_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('halaqa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.halaqa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='halaqa',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='halaqat_as_teacher', to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ayah', models.PositiveIntegerField(blank=True, null=True, verbose_name='من آية')),
                ('end_ayah', models.PositiveIntegerField(blank=True, null=True, verbose_name='إلى آية')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='الموعد النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_recitations', to='accounts.profile')),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='accounts.halaqa')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.surah', verbose_name='السورة')),
            ],
            options={
                'ordering': ['-deadline', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ayah', models.PositiveIntegerField(blank=True, null=True, verbose_name='من آية')),
                ('end_ayah', models.PositiveIntegerField(blank=True, null=True, verbose_name='إلى آية')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='الموعد النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_reviews', to='accounts.profile')),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.halaqa')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.surah', verbose_name='السورة')),
            ],
            options={
                'ordering': ['-deadline', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر')], default='present', max_length=10)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RecitationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('status', models.CharField(choices=[('submitted', 'تم التسليم'), ('reviewing', 'قيد المراجعة'), ('graded', 'تم التصحيح')], default='submitted', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rules', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hifdh', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.recitation')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='recitation_submissions', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('recitation', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('status', models.CharField(choices=[('submitted', 'تم التسليم'), ('reviewing', 'قيد المراجعة'), ('graded', 'تم التصحيح')], default='submitted', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rules', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hifdh', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.review')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='review_submissions', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('review', 'student')},
            },
        ),
    ]
