# Generated by Django 5.2.6 on 2025-09-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitation',
            name='end_ayah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recitation',
            name='start_ayah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
