# Generated by Django 5.2.6 on 2025-09-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recitation_end_ayah_recitation_start_ayah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('juz_from', models.PositiveSmallIntegerField()),
                ('juz_to', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='halaqa',
            name='juz_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='halaqa',
            name='juz_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
