# Generated by Django 5.2.6 on 2025-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_surah_halaqa_juz_from_halaqa_juz_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recitation',
            name='range_text',
        ),
        migrations.AlterField(
            model_name='recitation',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='الموعد النهائي'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='end_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إلى آية'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='start_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='من آية'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='surah',
            field=models.CharField(max_length=100, verbose_name='اسم السورة'),
        ),
    ]
