# Generated by Django 5.2.6 on 2025-09-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitationsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
