# Generated by Django 5.2.6 on 2025-09-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_recitationsubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
